Resources:
  CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: eugostitelji-user-pool
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 8
            RequireLowercase: false
            RequireNumbers: false
            RequireUppercase: false
            RequireSymbols: false
        UsernameAttributes:
          - email
        # TODO Add PostConfirmation lambda 

  WebUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: eugostitelji-pool-client
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
      
Outputs:
  UserPoolOutput:
    Value: !Ref CognitoUserPool
  ClientIdOutput: 
    Value: !Ref WebUserPoolClient
