Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: ${self:service}-${self:provider.stage}-assets
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - "PUT"
            AllowedOrigins:
              - "*"
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E1029
            - E3031
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "There is no need to keep access logs for this bucket"
          - id: W41
            reason: "There is no need to encrypt this bucket"

  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Ref AssetsBucket

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Statement:
          - Action: s3:GetObject
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt OriginAccessIdentity.S3CanonicalUserId
            Resource: !Sub "${AssetsBucket.Arn}/*"

  CloudFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: "http2"
        IPV6Enabled: true
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        Origins:
          - Id: assets
            DomainName: !GetAtt AssetsBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        DefaultCacheBehavior:
          TargetOriginId: assets
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          ForwardedValues:
            QueryString: false
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W70
            reason: "TLS protocol version is not relevant for this distribution"
          - id: W10
            reason: "There is no need to keep access logs for this distribution"
