Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ${self:service}-${self:provider.stage}
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireUppercase: false
          RequireSymbols: false
      UsernameAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: eugostitelji

  WebUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: ${self:service}-${self:provider.stage}-client
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E1029

  CognitoUserPoolModeratorGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Moderator
      UserPoolId: !Ref CognitoUserPool
      Precedence: 0

Outputs:
  UserPoolOutput:
    Value: !Ref CognitoUserPool
  ClientIdOutput:
    Value: !Ref WebUserPoolClient
