Resources:
  ServiceProviderTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.settings.SERVICE_PROVIDER_TABLE}
      BillingMode: PAY_PER_REQUEST

      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: dateCreated
          AttributeType: S
        - AttributeName: published
          AttributeType: N

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: publishedIndex
          KeySchema:
            - AttributeName: published
              KeyType: HASH
            - AttributeName: dateCreated
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
