Resources:
  ServiceProviderTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.settings.SERVICE_PROVIDER_TABLE}
      BillingMode: PAY_PER_REQUEST

      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: dateCreated
          AttributeType: S
        - AttributeName: published
          AttributeType: N

      KeySchema:
        - AttributeName: id
          KeyType: HASH

      GlobalSecondaryIndexes:
        - IndexName: publishedIndex
          KeySchema:
            - AttributeName: published
              KeyType: HASH
            - AttributeName: dateCreated
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E1029
      cfn_nag:
        rules_to_suppress:
          - id: W74
            reason: "There is no need to encrypt this table"
          - id: W28
            reason: "Resources is protected by stack policy"
