Resources:
  ServiceProviderTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.settings.searchTable}
      BillingMode: PAY_PER_REQUEST

      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH
