Resources:
  UserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.settings.userTable}
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH
