Resources:
  UserTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.settings.USER_TABLE}
      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

      KeySchema:
        - AttributeName: id
          KeyType: HASH
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E1029
      cfn_nag:
        rules_to_suppress:
          - id: W74
            reason: "There is no need to encrypt this table"
          - id: W28
            reason: "Resources is protected by stack policy"
